version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "covid"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5td7vm7sf5n"
s3_prefix = "covid"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
